version: '3'

tasks:
  start-infra:
    cmds:
      - docker compose up -d

  stop-infra:
    cmds:
      - docker compose down

  restart-infra:
    cmds:
      - task: stop-infra
      - timeout 1
      - task: start-infra