INSERT INTO topics (topic_id, title, sanitized_title, created_at)
VALUES (1,
        '21 şubat örnek tablo verilerinin yeniden yazılması',
        '21-subat-ornek-tablo-verilerinin-yeniden-yazilmasi',
        now()),

       (2,
        '20 şubat bir önceki gün verileri',
        '20-subat-bir-onceki-gun-verileri',
        now() - interval '1 day'),
       (3,
        '19 şubat verileri',
        '19-subat-verileri',
        now() - interval '2 day'),
       (4,
        '18 şubat verileri',
        '18-subat-verileri',
        now() - interval '3 day');


INSERT INTO definitions (topic_id, definition, created_at)
VALUES (1,
        '1 - Bir web sitesine ihtiyacım var sitenin içeriği , kısaca bahsedecek olursam site giriş sayfasında uye olacak kısıden kısa bilgi alınması devamında gelinen sayfadan 5 bolumden oluşan formdan detaylı bilgi alınması ve sonrasında index sayfasına ulaşıması ulaşılan index sayfasında story ve durum paylaşımın yapılması bir başkasının yaptığı paylaşımlar ile etkileşim(yorum yapma - begenme-gülümse...) yine aynı sayfadan kullanıcın 3 başlık altında 5 bolumden oluşan detaylı bilgi kısmının güncellenmesi veya yeni bilgilerin girişinin yapılması , aynı şekilde üye profil sayfasından da aynı güncellenmelerin yapılması işlemin dışında admin sayfalarının oluşturulmasını istemekteyim liste halinde anlatacak olursam',
        now()),
       (1,
        '2 - Bir web sitesine ihtiyacım var sitenin içeriği , kısaca bahsedecek olursam site giriş sayfasında uye olacak kısıden kısa bilgi alınması devamında gelinen sayfadan 5 bolumden oluşan formdan detaylı bilgi alınması ve sonrasında index sayfasına ulaşıması ulaşılan index sayfasında story ve durum paylaşımın yapılması bir başkasının yaptığı paylaşımlar ile etkileşim(yorum yapma - begenme-gülümse...) yine aynı sayfadan kullanıcın 3 başlık altında 5 bolumden oluşan detaylı bilgi kısmının güncellenmesi veya yeni bilgilerin girişinin yapılması , aynı şekilde üye profil sayfasından da aynı güncellenmelerin yapılması işlemin dışında admin sayfalarının oluşturulmasını istemekteyim liste halinde anlatacak olursam',
        now()),
       (1,
        '3 - Bir web sitesine ihtiyacım var sitenin içeriği , kısaca bahsedecek olursam site giriş sayfasında uye olacak kısıden kısa bilgi alınması devamında gelinen sayfadan 5 bolumden oluşan formdan detaylı bilgi alınması ve sonrasında index sayfasına ulaşıması ulaşılan index sayfasında story ve durum paylaşımın yapılması bir başkasının yaptığı paylaşımlar ile etkileşim(yorum yapma - begenme-gülümse...) yine aynı sayfadan kullanıcın 3 başlık altında 5 bolumden oluşan detaylı bilgi kısmının güncellenmesi veya yeni bilgilerin girişinin yapılması , aynı şekilde üye profil sayfasından da aynı güncellenmelerin yapılması işlemin dışında admin sayfalarının oluşturulmasını istemekteyim liste halinde anlatacak olursam',
        now()),


       (2,
        '1 - Bir web sitesine ihtiyacım var sitenin içeriği , kısaca bahsedecek olursam site giriş sayfasında uye olacak kısıden kısa bilgi alınması devamında gelinen sayfadan 5 bolumden oluşan formdan detaylı bilgi alınması ve sonrasında index sayfasına ulaşıması ulaşılan index sayfasında story ve durum paylaşımın yapılması bir başkasının yaptığı paylaşımlar ile etkileşim(yorum yapma - begenme-gülümse...) yine aynı sayfadan kullanıcın 3 başlık altında 5 bolumden oluşan detaylı bilgi kısmının güncellenmesi veya yeni bilgilerin girişinin yapılması , aynı şekilde üye profil sayfasından da aynı güncellenmelerin yapılması işlemin dışında admin sayfalarının oluşturulmasını istemekteyim liste halinde anlatacak olursam',
        now() - interval '1 day'),
       (2,
        '2 - Bir web sitesine ihtiyacım var sitenin içeriği , kısaca bahsedecek olursam site giriş sayfasında uye olacak kısıden kısa bilgi alınması devamında gelinen sayfadan 5 bolumden oluşan formdan detaylı bilgi alınması ve sonrasında index sayfasına ulaşıması ulaşılan index sayfasında story ve durum paylaşımın yapılması bir başkasının yaptığı paylaşımlar ile etkileşim(yorum yapma - begenme-gülümse...) yine aynı sayfadan kullanıcın 3 başlık altında 5 bolumden oluşan detaylı bilgi kısmının güncellenmesi veya yeni bilgilerin girişinin yapılması , aynı şekilde üye profil sayfasından da aynı güncellenmelerin yapılması işlemin dışında admin sayfalarının oluşturulmasını istemekteyim liste halinde anlatacak olursam',
        now() - interval '1 day'),
       (2,
        '3 - Bir web sitesine ihtiyacım var sitenin içeriği , kısaca bahsedecek olursam site giriş sayfasında uye olacak kısıden kısa bilgi alınması devamında gelinen sayfadan 5 bolumden oluşan formdan detaylı bilgi alınması ve sonrasında index sayfasına ulaşıması ulaşılan index sayfasında story ve durum paylaşımın yapılması bir başkasının yaptığı paylaşımlar ile etkileşim(yorum yapma - begenme-gülümse...) yine aynı sayfadan kullanıcın 3 başlık altında 5 bolumden oluşan detaylı bilgi kısmının güncellenmesi veya yeni bilgilerin girişinin yapılması , aynı şekilde üye profil sayfasından da aynı güncellenmelerin yapılması işlemin dışında admin sayfalarının oluşturulmasını istemekteyim liste halinde anlatacak olursam',
        now() - interval '1 day'),
       (2,
        '5 - Bir web sitesine ihtiyacım var sitenin içeriği , kısaca bahsedecek olursam site giriş sayfasında uye olacak kısıden kısa bilgi alınması devamında gelinen sayfadan 5 bolumden oluşan formdan detaylı bilgi alınması ve sonrasında index sayfasına ulaşıması ulaşılan index sayfasında story ve durum paylaşımın yapılması bir başkasının yaptığı paylaşımlar ile etkileşim(yorum yapma - begenme-gülümse...) yine aynı sayfadan kullanıcın 3 başlık altında 5 bolumden oluşan detaylı bilgi kısmının güncellenmesi veya yeni bilgilerin girişinin yapılması , aynı şekilde üye profil sayfasından da aynı güncellenmelerin yapılması işlemin dışında admin sayfalarının oluşturulmasını istemekteyim liste halinde anlatacak olursam',
        now()),
       (2,
        '6 - Bir web sitesine ihtiyacım var sitenin içeriği , kısaca bahsedecek olursam site giriş sayfasında uye olacak kısıden kısa bilgi alınması devamında gelinen sayfadan 5 bolumden oluşan formdan detaylı bilgi alınması ve sonrasında index sayfasına ulaşıması ulaşılan index sayfasında story ve durum paylaşımın yapılması bir başkasının yaptığı paylaşımlar ile etkileşim(yorum yapma - begenme-gülümse...) yine aynı sayfadan kullanıcın 3 başlık altında 5 bolumden oluşan detaylı bilgi kısmının güncellenmesi veya yeni bilgilerin girişinin yapılması , aynı şekilde üye profil sayfasından da aynı güncellenmelerin yapılması işlemin dışında admin sayfalarının oluşturulmasını istemekteyim liste halinde anlatacak olursam',
        now()),

       (3,
        '1 - Bir web sitesine ihtiyacım var sitenin içeriği , kısaca bahsedecek olursam site giriş sayfasında uye olacak kısıden kısa bilgi alınması devamında gelinen sayfadan 5 bolumden oluşan formdan detaylı bilgi alınması ve sonrasında index sayfasına ulaşıması ulaşılan index sayfasında story ve durum paylaşımın yapılması bir başkasının yaptığı paylaşımlar ile etkileşim(yorum yapma - begenme-gülümse...) yine aynı sayfadan kullanıcın 3 başlık altında 5 bolumden oluşan detaylı bilgi kısmının güncellenmesi veya yeni bilgilerin girişinin yapılması , aynı şekilde üye profil sayfasından da aynı güncellenmelerin yapılması işlemin dışında admin sayfalarının oluşturulmasını istemekteyim liste halinde anlatacak olursam',
        now() - interval '2 day'),
       (3,
        '2 - Bir web sitesine ihtiyacım var sitenin içeriği , kısaca bahsedecek olursam site giriş sayfasında uye olacak kısıden kısa bilgi alınması devamında gelinen sayfadan 5 bolumden oluşan formdan detaylı bilgi alınması ve sonrasında index sayfasına ulaşıması ulaşılan index sayfasında story ve durum paylaşımın yapılması bir başkasının yaptığı paylaşımlar ile etkileşim(yorum yapma - begenme-gülümse...) yine aynı sayfadan kullanıcın 3 başlık altında 5 bolumden oluşan detaylı bilgi kısmının güncellenmesi veya yeni bilgilerin girişinin yapılması , aynı şekilde üye profil sayfasından da aynı güncellenmelerin yapılması işlemin dışında admin sayfalarının oluşturulmasını istemekteyim liste halinde anlatacak olursam',
        now() - interval '2 day'),
       (3,
        '3 - Bir web sitesine ihtiyacım var sitenin içeriği , kısaca bahsedecek olursam site giriş sayfasında uye olacak kısıden kısa bilgi alınması devamında gelinen sayfadan 5 bolumden oluşan formdan detaylı bilgi alınması ve sonrasında index sayfasına ulaşıması ulaşılan index sayfasında story ve durum paylaşımın yapılması bir başkasının yaptığı paylaşımlar ile etkileşim(yorum yapma - begenme-gülümse...) yine aynı sayfadan kullanıcın 3 başlık altında 5 bolumden oluşan detaylı bilgi kısmının güncellenmesi veya yeni bilgilerin girişinin yapılması , aynı şekilde üye profil sayfasından da aynı güncellenmelerin yapılması işlemin dışında admin sayfalarının oluşturulmasını istemekteyim liste halinde anlatacak olursam',
        now() - interval '2 day'),
       (3,
        '5 - Bir web sitesine ihtiyacım var sitenin içeriği , kısaca bahsedecek olursam site giriş sayfasında uye olacak kısıden kısa bilgi alınması devamında gelinen sayfadan 5 bolumden oluşan formdan detaylı bilgi alınması ve sonrasında index sayfasına ulaşıması ulaşılan index sayfasında story ve durum paylaşımın yapılması bir başkasının yaptığı paylaşımlar ile etkileşim(yorum yapma - begenme-gülümse...) yine aynı sayfadan kullanıcın 3 başlık altında 5 bolumden oluşan detaylı bilgi kısmının güncellenmesi veya yeni bilgilerin girişinin yapılması , aynı şekilde üye profil sayfasından da aynı güncellenmelerin yapılması işlemin dışında admin sayfalarının oluşturulmasını istemekteyim liste halinde anlatacak olursam',
        now()),
       (3,
        '6 - Bir web sitesine ihtiyacım var sitenin içeriği , kısaca bahsedecek olursam site giriş sayfasında uye olacak kısıden kısa bilgi alınması devamında gelinen sayfadan 5 bolumden oluşan formdan detaylı bilgi alınması ve sonrasında index sayfasına ulaşıması ulaşılan index sayfasında story ve durum paylaşımın yapılması bir başkasının yaptığı paylaşımlar ile etkileşim(yorum yapma - begenme-gülümse...) yine aynı sayfadan kullanıcın 3 başlık altında 5 bolumden oluşan detaylı bilgi kısmının güncellenmesi veya yeni bilgilerin girişinin yapılması , aynı şekilde üye profil sayfasından da aynı güncellenmelerin yapılması işlemin dışında admin sayfalarının oluşturulmasını istemekteyim liste halinde anlatacak olursam',
        now()),

       (4,
        '1 - Bir web sitesine ihtiyacım var sitenin içeriği , kısaca bahsedecek olursam site giriş sayfasında uye olacak kısıden kısa bilgi alınması devamında gelinen sayfadan 5 bolumden oluşan formdan detaylı bilgi alınması ve sonrasında index sayfasına ulaşıması ulaşılan index sayfasında story ve durum paylaşımın yapılması bir başkasının yaptığı paylaşımlar ile etkileşim(yorum yapma - begenme-gülümse...) yine aynı sayfadan kullanıcın 3 başlık altında 5 bolumden oluşan detaylı bilgi kısmının güncellenmesi veya yeni bilgilerin girişinin yapılması , aynı şekilde üye profil sayfasından da aynı güncellenmelerin yapılması işlemin dışında admin sayfalarının oluşturulmasını istemekteyim liste halinde anlatacak olursam',
        now() - interval '3 day'),
       (4,
        '2 - Bir web sitesine ihtiyacım var sitenin içeriği , kısaca bahsedecek olursam site giriş sayfasında uye olacak kısıden kısa bilgi alınması devamında gelinen sayfadan 5 bolumden oluşan formdan detaylı bilgi alınması ve sonrasında index sayfasına ulaşıması ulaşılan index sayfasında story ve durum paylaşımın yapılması bir başkasının yaptığı paylaşımlar ile etkileşim(yorum yapma - begenme-gülümse...) yine aynı sayfadan kullanıcın 3 başlık altında 5 bolumden oluşan detaylı bilgi kısmının güncellenmesi veya yeni bilgilerin girişinin yapılması , aynı şekilde üye profil sayfasından da aynı güncellenmelerin yapılması işlemin dışında admin sayfalarının oluşturulmasını istemekteyim liste halinde anlatacak olursam',
        now() - interval '3 day'),
       (4,
        '3 - Bir web sitesine ihtiyacım var sitenin içeriği , kısaca bahsedecek olursam site giriş sayfasında uye olacak kısıden kısa bilgi alınması devamında gelinen sayfadan 5 bolumden oluşan formdan detaylı bilgi alınması ve sonrasında index sayfasına ulaşıması ulaşılan index sayfasında story ve durum paylaşımın yapılması bir başkasının yaptığı paylaşımlar ile etkileşim(yorum yapma - begenme-gülümse...) yine aynı sayfadan kullanıcın 3 başlık altında 5 bolumden oluşan detaylı bilgi kısmının güncellenmesi veya yeni bilgilerin girişinin yapılması , aynı şekilde üye profil sayfasından da aynı güncellenmelerin yapılması işlemin dışında admin sayfalarının oluşturulmasını istemekteyim liste halinde anlatacak olursam',
        now() - interval '3 day'),
       (4,
        '5 - Bir web sitesine ihtiyacım var sitenin içeriği , kısaca bahsedecek olursam site giriş sayfasında uye olacak kısıden kısa bilgi alınması devamında gelinen sayfadan 5 bolumden oluşan formdan detaylı bilgi alınması ve sonrasında index sayfasına ulaşıması ulaşılan index sayfasında story ve durum paylaşımın yapılması bir başkasının yaptığı paylaşımlar ile etkileşim(yorum yapma - begenme-gülümse...) yine aynı sayfadan kullanıcın 3 başlık altında 5 bolumden oluşan detaylı bilgi kısmının güncellenmesi veya yeni bilgilerin girişinin yapılması , aynı şekilde üye profil sayfasından da aynı güncellenmelerin yapılması işlemin dışında admin sayfalarının oluşturulmasını istemekteyim liste halinde anlatacak olursam',
        now()),
       (4,
        '6 - Bir web sitesine ihtiyacım var sitenin içeriği , kısaca bahsedecek olursam site giriş sayfasında uye olacak kısıden kısa bilgi alınması devamında gelinen sayfadan 5 bolumden oluşan formdan detaylı bilgi alınması ve sonrasında index sayfasına ulaşıması ulaşılan index sayfasında story ve durum paylaşımın yapılması bir başkasının yaptığı paylaşımlar ile etkileşim(yorum yapma - begenme-gülümse...) yine aynı sayfadan kullanıcın 3 başlık altında 5 bolumden oluşan detaylı bilgi kısmının güncellenmesi veya yeni bilgilerin girişinin yapılması , aynı şekilde üye profil sayfasından da aynı güncellenmelerin yapılması işlemin dışında admin sayfalarının oluşturulmasını istemekteyim liste halinde anlatacak olursam',
        now());